package com.luchienlin.mybatis.bean;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb1_dept.id
     *
     * @mbg.generated Tue Apr 21 10:18:10 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb1_dept.dept_name
     *
     * @mbg.generated Tue Apr 21 10:18:10 CST 2020
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb1_dept.id
     *
     * @return the value of tb1_dept.id
     *
     * @mbg.generated Tue Apr 21 10:18:10 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb1_dept.id
     *
     * @param id the value for tb1_dept.id
     *
     * @mbg.generated Tue Apr 21 10:18:10 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb1_dept.dept_name
     *
     * @return the value of tb1_dept.dept_name
     *
     * @mbg.generated Tue Apr 21 10:18:10 CST 2020
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb1_dept.dept_name
     *
     * @param deptName the value for tb1_dept.dept_name
     *
     * @mbg.generated Tue Apr 21 10:18:10 CST 2020
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }
}